import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Save, BrainCircuit, Workflow as WorkflowIcon } from 'lucide-react';
import { Skill, Workflow, tauriApi } from '@/api/tauri';
import { useToast } from '@/hooks/use-toast';

interface SkillEditorProps {
    skill: Skill;
    workflows?: Workflow[]; // Available workflows to check usage
    onSave: (updatedSkill: Skill) => void;
}

export default function SkillEditor({ skill, workflows = [], onSave }: SkillEditorProps) {
    const [name, setName] = useState(skill.name);
    const [description, setDescription] = useState(skill.description);
    const [template, setTemplate] = useState(skill.template || (skill as any).prompt_template || ''); // Handle inconsistent naming in types if any
    const [isSaving, setIsSaving] = useState(false);
    const [usedInWorkflows, setUsedInWorkflows] = useState<Workflow[]>([]);
    const { toast } = useToast();

    // Initialize state when skill changes
    useEffect(() => {
        setName(skill.name);
        setDescription(skill.description);
        // Fallback for template property naming differences
        setTemplate(skill.template || (skill as any).prompt_template || '');

        // Find workflows that use this skill
        if (workflows.length > 0) {
            const usingWorkflows = workflows.filter(workflow =>
                workflow.steps.some(step => step.config.skill_id === skill.id)
            );
            setUsedInWorkflows(usingWorkflows);
        } else {
            setUsedInWorkflows([]);
        }
    }, [skill, workflows]);

    const handleSave = async () => {
        if (!name.trim()) {
            toast({
                title: 'Validation Error',
                description: 'Skill name is required',
                variant: 'destructive'
            });
            return;
        }

        setIsSaving(true);
        try {
            const updatedSkill: Skill = {
                ...skill,
                name: name.trim(),
                description: description.trim(),
                template: template // The backend expects 'promptTemplate' mapped from 'template' or similar, strict typing might need adjustment
            };

            // We need to call the API to update
            // Since the API expects specific fields, let's verify exact structure
            // tauriApi.updateSkill takes a Skill object

            // Note: The Skill interface in frontend might slightly differ from backend expectation if not strictly autogenerated
            // Let's ensure we pass what's needed.

            await tauriApi.updateSkill(updatedSkill);

            toast({
                title: 'Success',
                description: 'Skill updated successfully'
            });

            onSave(updatedSkill);
        } catch (error) {
            console.error('Failed to update skill:', error);
            toast({
                title: 'Error',
                description: `Failed to update skill: ${error}`,
                variant: 'destructive'
            });
        } finally {
            setIsSaving(false);
        }
    };

    return (
        <div className="h-full flex flex-col bg-white dark:bg-gray-950 overflow-hidden">
            {/* Header */}
            <div className="border-b border-gray-200 dark:border-gray-800 p-4 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <div className="p-2 rounded-md bg-purple-50 dark:bg-purple-950/30 text-purple-600 dark:text-purple-400">
                        <BrainCircuit className="w-5 h-5" />
                    </div>
                    <div>
                        <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                            Edit Skill
                        </h2>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Configure skill behavior and prompt template
                        </p>
                    </div>
                </div>
                <Button
                    onClick={handleSave}
                    disabled={isSaving}
                    variant="default"
                    className="gap-2 bg-blue-600 hover:bg-blue-700 text-white"
                >
                    <Save className="w-4 h-4" />
                    {isSaving ? 'Saving...' : 'Save Changes'}
                </Button>
            </div>

            {/* Content having scroll */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6 max-w-4xl mx-auto w-full">

                {/* Usage Warning */}
                {usedInWorkflows.length > 0 && (
                    <div className="bg-orange-50 dark:bg-orange-950/20 border border-orange-100 dark:border-orange-900 rounded-lg p-4">
                        <div className="flex items-start gap-3">
                            <WorkflowIcon className="w-5 h-5 text-orange-600 dark:text-orange-400 mt-0.5" />
                            <div>
                                <h3 className="text-sm font-medium text-orange-800 dark:text-orange-300">
                                    Used in {usedInWorkflows.length} Workflow{usedInWorkflows.length !== 1 ? 's' : ''}
                                </h3>
                                <p className="text-sm text-orange-600 dark:text-orange-400 mt-1 mb-2">
                                    Changes to this skill will affect the following active workflows:
                                </p>
                                <div className="flex flex-wrap gap-2">
                                    {usedInWorkflows.map(wf => (
                                        <div key={wf.id} className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-orange-100 dark:bg-orange-900/40 text-xs font-medium text-orange-800 dark:text-orange-300 border border-orange-200 dark:border-orange-800">
                                            <span>{wf.name}</span>
                                            {/* Could add link to open workflow later */}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                )}

                <div className="grid gap-6 p-6 border border-gray-200 dark:border-gray-800 rounded-lg bg-gray-50/50 dark:bg-gray-900/50">
                    <div className="grid gap-2">
                        <Label htmlFor="skill-name">Skill Name</Label>
                        <Input
                            id="skill-name"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            className="bg-white dark:bg-gray-950"
                            placeholder="e.g. Research Assistant"
                        />
                    </div>

                    <div className="grid gap-2">
                        <Label htmlFor="skill-description">Description</Label>
                        <Input
                            id="skill-description"
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            className="bg-white dark:bg-gray-950"
                            placeholder="Brief description of what this skill does"
                        />
                    </div>
                </div>

                <div className="grid gap-2">
                    <div className="flex items-center justify-between">
                        <Label htmlFor="skill-template" className="text-base font-medium">Prompt Template</Label>
                        <span className="text-xs text-gray-500">
                            Supports markdown and {'{{variable}}'} placeholders
                        </span>
                    </div>
                    <div className="relative">
                        <Textarea
                            id="skill-template"
                            value={template}
                            onChange={(e) => setTemplate(e.target.value)}
                            className="min-h-[400px] font-mono text-sm leading-relaxed bg-white dark:bg-gray-950 resize-y p-4"
                            placeholder="# Role&#10;You are a...&#10;&#10;# Task&#10;Your task is to..."
                        />
                    </div>
                    <p className="text-xs text-gray-500 max-w-2xl">
                        Design the prompt that will be sent to the AI. Include Role, Context, and specific Instructions.
                        Variables can be inserted dynamically by workflows.
                    </p>
                </div>
            </div>
        </div>
    );
}
